[package]
name = "fur"
version = "0.1.0"
edition = "2021"
rust-version = "1.66.0"

[dependencies]
cosmic-text = { version="0.14.1", default-features=false, features=["no_std"] }
spin = "0.10.0"

[dev-dependencies]
minifb = "0.28.0"
