[package]
name = "fur"
version = "0.1.0"
edition = "2024"

[dependencies]
cosmic-text = {version="0.12.1", default-features=false, features=["no_std"]}
spin = "0.9.8"

[dev-dependencies]
minifb = "0.28.0"
